// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnvjnlieqcpileynoxco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udmpubGllcWNwaWxleW5veGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDIyMzMsImV4cCI6MjA2MTExODIzM30.iTKwABA5KTb0LYFuJ5gNtKwPnsbU5NT4qPQLRP-vBJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);